meals_list = [
'Chicken & Rice',
'Mealballs',
'Sausage & Mash',
'Chicken Pasta Bake',
'Bolognese',
'Curry',
'Tuna Pasta Bake',
'Sausage Casserole',
'Fruity Pork Steaks',
'Pie, Mash & Veg',
'Fajitas',
'Pulled Pork',
'3 Bean Chillie',
'Lamb Steaks',
'Beef Steaks',
'Jacket Potato',
'Risotto',
'Salad',
'Chicken Stew',
'Gammon Steaks',
'Omelette',
'Lasagne',
'Creamy Chicken Pasta'

]